name: Daily Tweet Bot
//hide by x wants py 20260427 sad 
//on:
//  schedule:
//    - cron: '0 1 * * *'
//  workflow_dispatch:
//
jobs:
if: false
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到 v4 以支持 Node.js 20+

      - name: Set up Python
        uses: actions/setup-python@v5 # 升级到 v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install tweepy

      - name: Run tweet script
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: python tweet.py
